---
- hosts: localhost
  tasks:
      - name: Delete IAM user 
        iam:
           iam_type: user
           name: "{{ item }}"
           state: absent
        with_items:
                - nitesh
                - itlearn360
